server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: auth-service

token:
  secret: ${TOKEN_SECRET:ticket-project-secret-value-is-made-by-random}
  accessTokenValidityInMilliseconds: 3600000
  refreshTokenValidityInMilliseconds: 1209600000

services:
  auth-service:
    url: "http://localhost:8080"
  user-service:
    url: "http://localhost:8081"
  ticket-service:
    url: "http://localhost:8082"