server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: auth-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "dev.bum.*"
    admin:
      properties:
        auto.create.topics.enable: false

token:
  secret: ${TOKEN_SECRET:ticket-project-secret-value-is-made-by-random}
  accessTokenValidityInMilliseconds: 1800000
  refreshTokenValidityInMilliseconds: 1209600000

topic:
  name: ${TOPIC_USER_EVENT_NAME:user-event}
  audit:
    log:
      name: ${TOPIC_AUDIT_LOG_NAME:audit-log}

services:
  auth-service:
    url: "http://localhost:8080"
  user-service:
    url: "http://localhost:8081"
  ticket-service:
    url: "http://localhost:8082"
