services:
  # 1. 데이터베이스 (Auth용)
  auth-db:
    image: postgres:16-alpine
    container_name: auth-db
    environment:
      - POSTGRES_USER=auth_user
      - POSTGRES_PASSWORD=auth_pass
      - POSTGRES_DB=auth_db
    ports:
      - "5433:5432"
    networks:
      - ticket-network
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  # 2. Redis (공통)
  refresh-redis:
    image: redis:latest
    container_name: refresh-redis
    ports:
      - "6379:6379"
    networks:
      - ticket-network # 이 서비스가 사용할 네트워크 지정
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    #restart: always # 컴퓨터 재부팅 시 자동 실행 (추천)

# 네트워크 정의 부분
networks:
  ticket-network:
    external: true # 수동으로 만든(docker network create) 네트워크를 사용함

volumes:
  auth_db_data:
  redis_data: