server:
  port: 8083
  servlet:
    context-path: /queue

spring:
  profiles:
    default: local
  application:
    name: queue-service
  data:
    redis:
      host: localhost
      port: 6381

token:
  secret: ticket-project-secret-value-is-made-by-random

app:
  queue:
    admission-size: 100
    token-ttl: 20m

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: ${MANAGEMENT_TRACING_SAMPLING_PROBABILITY:1.0}
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:http://localhost:4318/v1/traces}

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
