server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: audit-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
    consumer:
      group-id: ${KAFKA_AUDIT_GROUP_ID:audit-service-group}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "dev.bum.*"
    admin:
      properties:
        auto.create.topics.enable: false

topic:
  audit:
    log:
      name: ${TOPIC_AUDIT_LOG_NAME:audit-log}
