server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    admin:
      properties:
        auto.create.topics.enable: false

token:
  secret: ${TOKEN_SECRET:ticket-project-secret-value-is-made-by-random}

topic:
  name: ${TOPIC_USER_EVENT_NAME:user-event}
  audit:
    log:
      name: ${TOPIC_AUDIT_LOG_NAME:audit-log}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    tags:
      application: ${spring.application.name}
