server:
  port: 8999
  servlet:
    context-path: /admin

spring:
  application:
    name: admin-service

token:
  secret: ${TOKEN_SECRET:ticket-project-secret-value-is-made-by-random}
  accessTokenValidityInMilliseconds: 3600000
  refreshTokenValidityInMilliseconds: 1209600000

services:
  auth-service:
    url: "http://auth-service:8080"
  user-service:
    url: "http://user-service:8080"
  ticket-service:
    url: "http://ticket-service:8080"
