services:
  ingress-nginx:
    build:
      context: ../..
      dockerfile: infra/infra-ingress/Dockerfile
    container_name: ingress-nginx
    ports:
      - "80:80"
    networks:
      - ticket-network

networks:
  ticket-network:
    external: true
