INSERT INTO events (
    artist_name,
    title,
    event_group_code,
    description,
    venue,
    venue_address,
    poster_url,
    event_date_time,
    sale_start_at,
    sale_end_at,
    cancel_deadline_at,
    running_minutes,
    age_limit,
    total_seats,
    available_seats,
    status,
    max_tickets_per_person,
    ticket_limit_scope,
    genre,
    region,
    theme
)
SELECT
    artist_name,
    title,
    event_group_code,
    description,
    venue,
    venue_address,
    poster_url,
    event_date_time,
    sale_start_at,
    sale_end_at,
    cancel_deadline_at,
    running_minutes,
    age_limit,
    total_seats,
    available_seats,
    status,
    max_tickets_per_person,
    ticket_limit_scope,
    genre,
    region,
    theme
FROM (
    VALUES
        (
            'Ticksy Live Band',
            'Ticksy Live Festa',
            'TICKSY_LIVE_FESTA_2026',
            '여름밤 야외 무대에서 열리는 밴드 라이브 페스티벌입니다.',
            '서울월드컵공원 평화광장',
            '서울특별시 마포구 하늘공원로 86',
            '/ticket/uploads/events/posters/sample/ticksy-live-festa.png',
            '2026-09-05 19:00:00'::timestamp,
            '2026-08-01 14:00:00'::timestamp,
            '2026-09-04 23:59:59'::timestamp,
            '2026-09-03 23:59:59'::timestamp,
            180,
            12,
            20000,
            18420,
            'ON_SALE',
            4,
            'PER_EVENT',
            'CONCERT',
            'SEOUL',
            'FESTIVAL'
        ),
        (
            '서울 심포닉 오케스트라',
            '서울 오케스트라 갈라',
            'SEOUL_ORCHESTRA_GALA_2026',
            '대표 클래식 레퍼토리를 한자리에서 만나는 갈라 콘서트입니다.',
            '예술의전당 콘서트홀',
            '서울특별시 서초구 남부순환로 2406',
            '/ticket/uploads/events/posters/sample/seoul-orchestra-gala.png',
            '2026-09-11 20:00:00'::timestamp,
            '2026-08-05 11:00:00'::timestamp,
            '2026-09-10 23:59:59'::timestamp,
            '2026-09-09 23:59:59'::timestamp,
            120,
            8,
            2500,
            860,
            'ON_SALE',
            2,
            'PER_EVENT',
            'CLASSIC',
            'SEOUL',
            'OVERSEAS_PERFORMANCE'
        ),
        (
            'Aster Day',
            '팬미팅 스페셜 데이',
            'FANMEETING_SPECIAL_DAY_2026',
            '아티스트와 팬이 가까이 만나는 토크와 미니 라이브 이벤트입니다.',
            '블루스퀘어 마스터카드홀',
            '서울특별시 용산구 이태원로 294',
            '/ticket/uploads/events/posters/sample/fanmeeting-special-day.png',
            '2026-09-20 17:00:00'::timestamp,
            '2026-08-12 20:00:00'::timestamp,
            '2026-09-19 23:59:59'::timestamp,
            '2026-09-18 23:59:59'::timestamp,
            100,
            8,
            1400,
            312,
            'ON_SALE',
            1,
            'PER_EVENT',
            'FANCLUB_FANMEETING',
            'SEOUL',
            'IDOL'
        ),
        (
            '모던 아트 앙상블',
            '아트 뮤지엄 나이트',
            'ART_MUSEUM_NIGHT_2026',
            '전시 관람과 라이브 공연이 결합된 야간 뮤지엄 프로그램입니다.',
            'DDP 아트홀',
            '서울특별시 중구 을지로 281',
            '/ticket/uploads/events/posters/sample/art-museum-night.png',
            '2026-10-03 18:00:00'::timestamp,
            '2026-08-18 10:00:00'::timestamp,
            '2026-10-02 23:59:59'::timestamp,
            '2026-10-01 23:59:59'::timestamp,
            210,
            12,
            3200,
            2210,
            'ON_SALE',
            4,
            'PER_EVENT',
            'EXHIBITION_EVENT',
            'SEOUL',
            'SMALL_THEATER'
        ),
        (
            'Black Amp',
            '락 온 더 스테이지',
            'ROCK_ON_THE_STAGE_2026',
            '강렬한 기타 사운드와 무대 연출을 중심으로 한 락 콘서트입니다.',
            'YES24 라이브홀',
            '서울특별시 광진구 구천면로 20',
            '/ticket/uploads/events/posters/sample/rock-on-the-stage.png',
            '2026-10-10 19:30:00'::timestamp,
            '2026-08-21 18:00:00'::timestamp,
            '2026-10-09 23:59:59'::timestamp,
            '2026-10-08 23:59:59'::timestamp,
            150,
            15,
            2200,
            1498,
            'ON_SALE',
            2,
            'PER_EVENT',
            'CONCERT',
            'SEOUL',
            'SMALL_THEATER'
        )
) AS sample_events (
    artist_name,
    title,
    event_group_code,
    description,
    venue,
    venue_address,
    poster_url,
    event_date_time,
    sale_start_at,
    sale_end_at,
    cancel_deadline_at,
    running_minutes,
    age_limit,
    total_seats,
    available_seats,
    status,
    max_tickets_per_person,
    ticket_limit_scope,
    genre,
    region,
    theme
)
WHERE NOT EXISTS (
    SELECT 1
    FROM events
    WHERE events.event_group_code = sample_events.event_group_code
);
