DROP TABLE IF EXISTS user_login_locks;
DROP TABLE IF EXISTS auth CASCADE;

CREATE TABLE auth (
    id BIGINT PRIMARY KEY,
    user_id VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'ROLE_USER',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    is_blacklisted BOOLEAN NOT NULL DEFAULT FALSE,
    blacklisted_until DATE
);

CREATE INDEX idx_auth_user_id ON auth(user_id);

-- 계정별 연속 로그인 실패와 비밀번호 재설정 전까지 유지되는 잠금을 관리한다.
CREATE TABLE user_login_locks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_id BIGINT NOT NULL UNIQUE REFERENCES auth(id) ON DELETE CASCADE,
    failed_attempts INTEGER NOT NULL DEFAULT 0 CHECK (failed_attempts BETWEEN 0 AND 5),
    last_failed_at TIMESTAMP,
    locked_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_user_login_lock_state CHECK (
        (failed_attempts < 5 AND locked_at IS NULL)
        OR (failed_attempts = 5 AND locked_at IS NOT NULL)
    )
);
