DROP TABLE IF EXISTS auth CASCADE;

CREATE TABLE auth (
    id BIGINT PRIMARY KEY,
    user_id VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'ROLE_USER'
);

CREATE INDEX idx_auth_user_id ON auth(user_id);