global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: ticket-services
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - auth-service:8080
        labels:
          application: auth-service
          group: application
      - targets:
          - user-service:8080
        labels:
          application: user-service
          group: application
      - targets:
          - ticket-service:8080
        labels:
          application: ticket-service
          group: application
      - targets:
          - queue-service:8080
        labels:
          application: queue-service
          group: application
      - targets:
          - audit-service:8080
        labels:
          application: audit-service
          group: application

  - job_name: admin-service
    metrics_path: /admin/actuator/prometheus
    static_configs:
      - targets:
          - admin-service:8999
        labels:
          application: admin-service
          group: application

  - job_name: view-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - view-service:3000
        labels:
          application: view-service
          group: frontend
