server:
  port: 8080

spring:
  application:
    name: ticket-service
  datasource:
    driver-class-name: org.postgresql.Driver
    # 환경변수가 있으면 쓰고, 없으면 비워둠 (가독성 유지)
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      jdbc:
        batch_size: 500  # 500개씩 모아서 처리
        order_inserts: true
        order_updates: true
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer # 직렬화(S)가 아니라 역직렬화(D)!
      properties:
        spring.json.trusted.packages: "dev.bum.*"
    admin:
      properties:
        auto.create.topics.enable: false
token:
  secret: ${TOKEN_SECRET:ticket-project-secret-value-is-made-by-random}
  accessTokenValidityInMilliseconds: 3600000
  refreshTokenValidityInMilliseconds: 1209600000

topic:
  reservation:
    name: reservation-event

app:
  upload:
    root: ${APP_UPLOAD_ROOT:/app/uploads}
    public-url-prefix: ${APP_UPLOAD_PUBLIC_URL_PREFIX:/ticket/uploads}
