server:
  port: 8082

spring:
  application:
    name: ticket-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ticket
    username: postgres
    password: hsck2301
  jpa:
    hibernate:
      ddl-auto: update
      jdbc:
        batch_size: 500  # 500개씩 모아서 처리
        order_inserts: true
        order_updates: true

token:
  secret: ticket-project-secret-value-is-made-by-random
  accessTokenValidityInMilliseconds: 3600000
  refreshTokenValidityInMilliseconds: 1209600000
